model_name_or_path: /root/autodl-tmp/Qwen3-4B-Base/
stage: sft
dataset: maven_sft
dataset_dir: data/processed/maven_sft.jsonl
output_dir: /root/autodl-tmp/qwen-4b-mypretrain
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 1
save_steps: 10
logging_steps: 10
bf16: true
report_to: none